name: 'Release: awdur'
on:
  push:
    branches:
    - release
    paths:
    - 'lib/awdur/**'

permissions: {}

jobs:
  release:
    name: awdur release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/awdur
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: true  # needed to push commits to the release branch

    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: "3.12"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade build hatch towncrier docutils
      name: Setup Environment

    - run: |
        set -e

        ./scripts/make_release.py lib
      name: Set Version
      id: info

    - name: Package
      run: |
        cd lib/awdur
        python -m build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'dist'
        path: lib/awdur/dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
      with:
        packages-dir: lib/awdur/dist/

    - name: Create Release
      run: |
        gh release create "${RELEASE_TAG}" \
          --title "Awdur v${VERSION} - ${RELEASE_DATE}" \
          -F lib/awdur/.changes.md \
          ./lib/awdur/dist/*
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
